name: linting-workflow
on:
  push:
    branches:
        - develop
  pull_request:
    branches:
        - develop
jobs:
  linting_job:
    runs-on: ubuntu-latest
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: install HTML Hint
        run: npm install --save-dev htmlhint
      - name: Add HTML Hint file
        run: npx htmlhint "**/*.html"
      - name: install Css Lint
        run: npm install --save-dev stylelint
      - name: Add Style Lint file
        run: npx stylelint "**/*.css"